FROM node:14-alpine3.14 as builder

WORKDIR /usr/src/app/
USER root
COPY package.json ./
COPY yarn.lock /usr/src/app/yarn.lock
RUN yarn

COPY ./ ./

RUN npm run build:dev


FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html/

COPY ./docker/nginx-dev.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/src/app/dist  /usr/share/nginx/html/

COPY ./docker/dj_static /home/dj_myapp/static

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
